#!/bin/bash
# ===========================================================================
# init-gcp.sh — Google Cloud Infrastructure Setup
# Generated by AI Studio Architect (Agy Skill)
#
# This script provisions all GCP resources required to run an AI Studio
# Build mode application. Adapt and validate this scaffold before execution;
# existing-resource checks alone do not make every operation idempotent.
#
# Usage:
#   chmod +x init-gcp.sh
#   ./init-gcp.sh                    # Execute normally
#   DRY_RUN=true ./init-gcp.sh      # Print commands without executing
#
# Prerequisites:
#   - gcloud CLI installed and authenticated
#   - Billing enabled on the target project
# ===========================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# 1. CONFIGURATION
# Modify these variables for your project.
# ---------------------------------------------------------------------------
PROJECT_ID="${PROJECT_ID:-your-project-id}"
REGION="${REGION:-us-central1}"
SERVICE_NAME="${SERVICE_NAME:-my-app}"
SERVICE_ACCOUNT_NAME="${SERVICE_ACCOUNT_NAME:-${SERVICE_NAME}-sa}"
SERVICE_ACCOUNT_EMAIL="${SERVICE_ACCOUNT_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"

# Storage
BUCKET_NAME="${BUCKET_NAME:-${PROJECT_ID}-${SERVICE_NAME}-assets}"

# Firestore
FIRESTORE_DATABASE="${FIRESTORE_DATABASE:-(default)}"

# Dry run mode
DRY_RUN="${DRY_RUN:-false}"

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------
run() {
  if [ "$DRY_RUN" = "true" ]; then
    echo "[DRY RUN] $*"
  else
    echo "[RUNNING] $*"
    "$@"
  fi
}

section() {
  echo ""
  echo "================================================================"
  echo "  $1"
  echo "================================================================"
}

# ---------------------------------------------------------------------------
# 2. PROJECT SETUP
# Use an explicit project and verify billing is enabled.
# ---------------------------------------------------------------------------
section "Project Setup"

echo "Target project: $PROJECT_ID (commands use explicit --project)"

echo "Verifying billing is enabled..."
if [ "$DRY_RUN" != "true" ]; then
  BILLING=$(gcloud billing projects describe "$PROJECT_ID" --format="value(billingEnabled)")
  if [ "$BILLING" != "True" ]; then
    echo "ERROR: Billing is not enabled for project $PROJECT_ID."
    echo "Enable it at: https://console.cloud.google.com/billing/linkedaccount?project=$PROJECT_ID"
    exit 1
  fi
  echo "Billing is enabled."
fi

# ---------------------------------------------------------------------------
# 3. ENABLE APIs
# Enable all required Google Cloud APIs. This is idempotent.
# ---------------------------------------------------------------------------
section "Enabling APIs"

APIS=(
  # PLACEHOLDER: The skill will populate this list based on detected services.
  # Example entries:
  # aiplatform.googleapis.com
  # run.googleapis.com
  # firestore.googleapis.com
  # storage.googleapis.com
  # secretmanager.googleapis.com
)

if [ ${#APIS[@]} -gt 0 ]; then
  run gcloud services enable "${APIS[@]}" --project="$PROJECT_ID"
else
  echo "No APIs to enable. Update the APIS array in this script."
fi

# ---------------------------------------------------------------------------
# 4. SERVICE ACCOUNT
# Create a dedicated service account with least-privilege roles.
# Never use the default compute service account in production.
# ---------------------------------------------------------------------------
section "Service Account"

# A failed inspection must stop execution, never imply a missing resource.
EXISTING_ACCOUNT=""
if [ "$DRY_RUN" != "true" ]; then
  EXISTING_ACCOUNT=$(gcloud iam service-accounts list --project="$PROJECT_ID" \
    --filter="email=$SERVICE_ACCOUNT_EMAIL" --format="value(email)")
fi
if [ -z "$EXISTING_ACCOUNT" ]; then
  run gcloud iam service-accounts create "$SERVICE_ACCOUNT_NAME" \
    --display-name="${SERVICE_NAME} Service Account" \
    --project="$PROJECT_ID"
  if [ "$DRY_RUN" != "true" ]; then echo "Created service account: $SERVICE_ACCOUNT_EMAIL"; fi
else
  echo "Service account already exists: $SERVICE_ACCOUNT_EMAIL"
fi

# Bind IAM roles
# PLACEHOLDER: The skill will add role bindings based on detected services.
# Example:
# run gcloud projects add-iam-policy-binding "$PROJECT_ID" \
#   --member="serviceAccount:$SERVICE_ACCOUNT_EMAIL" \
#   --role="roles/aiplatform.user" \
#   --condition=None \
#   --quiet

# ---------------------------------------------------------------------------
# 5–8. OPTIONAL RESOURCES
# Add only services required by the inspected application.
# For each resource: inspect existence with a command whose failures stop the
# script, validate immutable location/settings, and route mutations through run.
# Guard read calls in dry-run mode too. Never interpret any CLI error as absence.
# Firestore: select the explicit database ID and supported database location.
# Storage: retain private access; use exact frontend origins for necessary CORS.
# Secrets: never create placeholder credential versions or echo secret values.
# Cloud Run: preserve auth policy; use --no-allow-unauthenticated by default,
# explicit --project/--region and the dedicated runtime service account.
# Validate deployment separately before reporting a working application URL.
# ---------------------------------------------------------------------------
# 9. OUTPUT SUMMARY
# ---------------------------------------------------------------------------
if [ "$DRY_RUN" = "true" ]; then
  section "Dry Run Complete — no cloud commands executed"
else
  section "Configured Setup Steps Complete"
fi

echo "Project:          $PROJECT_ID"
echo "Region:           $REGION"
echo "Service Account:  $SERVICE_ACCOUNT_EMAIL"
# echo "Bucket:           gs://$BUCKET_NAME"
# echo "Cloud Run URL:    $SERVICE_URL"
echo ""
echo "Next steps:"
echo "  1. Update secrets in Secret Manager with real values."
echo "  2. Build and deploy your application to Cloud Run."
echo "  3. Configure a custom domain (optional)."
echo "  4. Set up Cloud Monitoring dashboards."
